name: "teste copy"
on:
    issue_comment:
        types: [created]
jobs:
    copy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ./
              with:
                keyword: "/copy"
                targetRepository: recepcaoimeusp/guiadobixe
                githubToken: ${{ secrets.GITHUB_TOKEN }}
                contentOfNewIssue: 'prefix of newly created issue'
